language: csharp
solution: src/KiwiLanguage.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore src/KiwiLanguage.sln
after_script:
  - nunit-console Kiwi.Tests/bin/Release/Kiwi.Tests.dll