language: csharp
solution: src/KiwiLanguage.sln
install:
  - nuget restore src/KiwiLanguage.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/KiwiLanguage.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Kiwi.Tests/bin/Release/Kiwi.Tests.dll