language: csharp
solution: KiwiLanguage.sln
install:
  - nuget restore KiwiLanguage.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release KiwiLanguage.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Kiwi.Tests/bin/Release/Kiwi.Tests.dll